---
# tasks file for install_docker
- name: Install HTTPS packages for Docker
  apt: name={{ item }} state=latest update_cache=true
  loop:
    - ca-certificates
    - curl
    - gnupg
    - lsb-release
- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present
- name: Install Docker packages
  apt: name={{ item }} state=latest update_cache=true
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-compose-plugin
- name: Check docker is active
  service:
    name: docker
    state: started
    enabled: yes
- name: Install Pip
  apt: name=python3-pip state=latest update_cache=true
- name: Install Docker Module for Python
  pip: name=docker
