---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-{{ .Values.metadata.name }}
  labels:
    app  : {{ .Values.metadata.app }}
    env  : {{ .Values.metadata.env }}
    owner: {{ .Values.metadata.owner }}
  annotations:
    last_modified_date : {{ .Values.metadata.annotations.last_modified_date }}
    responsible_release: {{ .Values.metadata.annotations.responsible_release }}
spec:
  rules:
   - host: {{ .Values.ingress.host }}
     http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: service-{{ .Values.metadata.name }}
                port:
                  number: {{ .Values.service.port }}
