---
- name: Install Docker
  hosts: all
  become: yes
  roles:
    - install_docker

- name: Initialize Docker Swarm
  hosts: all
  become: yes
  roles:
    - docker_swarm_init

- name: Add Managers to the Swarm
  hosts: swarm_managers
  become: yes
  roles:
    - docker_swarm_add_manager

- name: Add Workers to the Swarm
  hosts: swarm_workers
  become: yes
  roles:
    - docker_swarm_add_worker

- name: Deploy Docker Stack Minio
  hosts: all
  become: yes
  roles:
    - deploy_docker_stack_minio
