---
- name: Install Gnupg2
  apt: name=gnupg2 state=latest update_cache=true

- name: Add Repository for PostgreSQL-14
  shell: 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'

- name: Add PostgreSQL-14 apt Key
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present

- name: Install PostgreSQL-14
  apt: name=postgresql-14 state=latest update_cache=true

- name: Ensure the PostgreSQL service is running
  service: name=postgresql state=started enabled=yes
