---
- name: "Check Docker package status"
  package:
    name: "{{ item }}"
    state: present
  check_mode: yes
  register: pkg_status
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-compose-plugin
- name: "Docker - test docker package is installed"
  assert:
    that:
      - not pkg_status.changed
